version: '3'

services:
    dressforecast_api:
        image: httpd
        container_name: dressforecast_web
        restart: always
        ports:
            - ${WEB_PORT}:80
        networks:
            - dressforecast-network
        volumes:
            - ./src:/usr/local/apache2/htdocs

networks:
    dressforecast-network:
        name: dressforecast-network
        driver: bridge